### ISSUE TITLE
Change README from Markdown to ReStructured Text

### ISSUE THREAD

**Issue by seporaitis** [YPlan/salesforce-oauth-request#4]
Because [PyPi](https://pypi.python.org/pypi?name=salesforce-oauth-request-yplan&version=1.1.0&:action=display) cannot render Markdown.

**Comment by adamchainz** [comment]
`pandoc -f markdown -t rst < README.md >README.rst`

**Comment by seporaitis** [comment]
Well... that makes it easy!

**Comment by adamchainz** [comment]
Often it needs touching up afterwards but yes it's quite straightforward
